### CREATE BASKET
POST http://localhost:8080/baskets
Accept: application/json

### FIND BASKET
GET http://localhost:8080/baskets/b9d1896b-99e1-4bd0-969f-01f27bf0a9f3
Accept: application/json

### DELETE BASKET
DELETE http://localhost:8080/baskets/b9d1896b-99e1-4bd0-969f-01f27bf0a9f3
Accept: application/json

### CREATE PRODUCT
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "{{$uuid}}",
  "stock": {{$randomInt}},
  "priceAmount": 36.99,
  "priceCurrency": "PLN"
}

### ADD PRODUCT
PUT http://localhost:8080/baskets/b9d1896b-99e1-4bd0-969f-01f27bf0a9f3/add/e9898e20-a473-4898-ade6-d75bdf7b7c04
Accept: application/json

### REMOVE PRODUCT
DELETE http://localhost:8080/baskets/b9d1896b-99e1-4bd0-969f-01f27bf0a9f3/remove/e9898e20-a473-4898-ade6-d75bdf7b7c04
Accept: application/json
